-   repo: git://github.com/antonbabenko/pre-commit-terraform
    sha: v1.2.0
    hooks:
      -   id: terraform_fmt

-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
      -   id: check-yaml
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-case-conflict
      -   id: check-merge-conflict
