- repo: git://github.com/antonbabenko/pre-commit-terraform
  sha: v1.5.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate_with_variables

- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v1.2.3
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: trailing-whitespace
