version: 2
jobs:
  build:
    docker:
       - image: hashicorp/terraform:light
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Execute a terraform init
          command: terraform init -upgrade -input=false
      - run:
          name: Execute a terraform plan
          command: terraform plan -detailed-exitcode -lock-timeout=2s -no-color -input=false
